### ISSUE TITLE
param文件编辑问题

### ISSUE THREAD

**Issue by Antactz** [obaby/skip_ads_android_ncnn_project#1]
你好，我想问下我自己转换得到的param文件，为什么我的前面10层并不是split,crop,concat这些层？我的pt权重文件是用yolov5s.pt训练的，用的是原始的yolov5源码，其他地方都没有改过

**Comment by obaby** [comment]
我的项目修改了一些配置参数，可以看下我的配置信息http://h4ck.org.cn/2021/09/android-skip-ads-yolov5-project/
